# Generated by Django 4.2.3 on 2023-07-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='app',
            name='icon_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='app',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='sub_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
